<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ot_events"
 *
 * Auto generated by Extension Builder 2015-03-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Eventcalendar',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Soeren Kroell',
	'author_email' => 'hallo@soerenkroell.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);